In [1]:
import pandas as pd

In [3]:
df =pd.read_csv(r"C:\Users\Raja\Documents\HR_Project\Dataset\HR_Analytics-4.csv")
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
0,VK2970,19,18-25,Yes,Travel_Rarely,230,Administration,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,VK3020,19,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,VK4580,19,18-25,Yes,Travel-Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,VK7280,19,18-25,No,Non-Travel,287,Administration,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,VK8290,19,18-25,Yes,Non-Travel,247,Administration,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [6]:
df.shape

(1480, 37)

In [5]:
print(df.isnull().sum())

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome(KM)         0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
HourlyRate                   0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
SalaryHike %                 0
PerformanceRating            0
RelationshipSatisfaction     0
StandardWorkingHours         0
StockOptionLevel             0
TotalExperience(Years)       0
TrainingsLastYear            0
WorkLifeBalance              0
YearsatCompany               0
YearsinCurrentRole           0
YearsSincePromotion          0
YearsWithCurrManager        61
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(61)

In [8]:
df[df['YearsWithCurrManager'].isnull()]

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome(KM),Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
28,VK0240,21,18-25,No,Travel_Rarely,391,Administration,15,2,Life Sciences,...,4,80,0,0,6,3,0,0,0,NaN
31,VK3630,22,18-25,No,Non-Travel,895,Sales,9,2,Medical,...,3,80,0,3,3,2,3,2,2,NaN
45,VK2070,22,18-25,No,Travel_Rarely,1136,Administration,5,3,Life Sciences,...,1,80,1,4,2,2,4,2,2,NaN
99,VK1390,25,18-25,No,Travel_Rarely,959,Sales,28,3,Life Sciences,...,4,80,0,6,3,3,2,2,2,NaN
100,VK2560,25,18-25,No,Travel_Rarely,685,Administration,1,3,Life Sciences,...,4,80,2,5,3,3,4,2,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360,VK4070,52,46-55,No,Travel_Rarely,319,Operations,3,3,Medical,...,3,80,0,28,4,3,5,4,0,NaN
1375,VK0260,53,46-55,No,Travel_Rarely,1282,Operations,5,3,Other,...,4,80,1,26,3,2,14,13,4,NaN
1448,VK3610,57,55+,No,Travel_Rarely,593,Operations,1,4,Medical,...,3,80,0,15,2,3,3,2,1,NaN
1465,VK0070,59,55+,No,Travel_Rarely,1324,Operations,3,3,Medical,...,1,80,3,12,3,2,1,0,0,NaN
1467,VK0710,59,55+,No,Travel-Frequently,1225,Sales,1,1,Life Sciences,...,4,80,0,20,2,2,4,3,1,NaN

In [11]:
df['YearsWithCurrManager']=df['YearsWithCurrManager'].fillna(df['YearsWithCurrManager'].median())

In [13]:
df['YearsWithCurrManager'].isnull().sum()

np.int64(0)

In [14]:
df.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome(KM)        0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
HourlyRate                  0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
SalaryHike %                0
PerformanceRating           0
RelationshipSatisfaction    0
StandardWorkingHours        0
StockOptionLevel            0
TotalExperience(Years)      0
TrainingsLastYear           0
WorkLifeBalance             0
YearsatCompany              0
YearsinCurrentRole          0
YearsSincePromotion         0
YearsWithCurrManager        0
dtype: int64

In [15]:
df.isnull().sum().sum()

np.int64(0)

In [16]:
df.duplicated().sum()

np.int64(2)

In [17]:
df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.shape

(1478, 37)

In [20]:
df.columns.tolist()

['EmpID',
 'Age',
 'AgeGroup',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome(KM)',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'SalarySlab',
 'HourlyRate',
 'NumCompaniesWorked',
 'Over18',
 'OverTime',
 'SalaryHike %',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardWorkingHours',
 'StockOptionLevel',
 'TotalExperience(Years)',
 'TrainingsLastYear',
 'WorkLifeBalance',
 'YearsatCompany',
 'YearsinCurrentRole',
 'YearsSincePromotion',
 'YearsWithCurrManager']

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1478 entries, 0 to 1479
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1478 non-null   object
 1   Age                       1478 non-null   int64
 2   AgeGroup                  1478 non-null   object
 3   Attrition                 1478 non-null   object
 4   BusinessTravel            1478 non-null   object
 5   DailyRate                 1478 non-null   int64
 6   Department                1478 non-null   object
 7   DistanceFromHome(KM)      1478 non-null   int64
 8   Education                 1478 non-null   int64
 9   EducationField            1478 non-null   object
 10  EmployeeCount             1478 non-null   int64
 11  EmployeeNumber            1478 non-null   int64
 12  EnvironmentSatisfaction   1478 non-null   int64
 13  Gender                    1478 non-null   object
 14  JobInvolvement            1478 non-null   int64
 15  JobLevel                  1478 non-null   int64
 16  JobRole                   1478 non-null   object
 17  JobSatisfaction           1478 non-null   int64
 18  MaritalStatus             1478 non-null   object
 19  MonthlyIncome             1478 non-null   int64
 20  SalarySlab                1478 non-null   object
 21  HourlyRate                1478 non-null   float64
 22  NumCompaniesWorked        1478 non-null   int64
 23  Over18                    1478 non-null   object
 24  OverTime                  1478 non-null   object
 25  SalaryHike %              1478 non-null   int64
 26  PerformanceRating         1478 non-null   int64
 27  RelationshipSatisfaction  1478 non-null   int64
 28  StandardWorkingHours      1478 non-null   int64
 29  StockOptionLevel          1478 non-null   int64
 30  TotalExperience(Years)    1478 non-null   int64
 31  TrainingsLastYear         1478 non-null   int64
 32  WorkLifeBalance           1478 non-null   int64
 33  YearsatCompany            1478 non-null   int64
 34  YearsinCurrentRole        1478 non-null   int64
 35  YearsSincePromotion       1478 non-null   int64
 36  YearsWithCurrManager      1478 non-null   float64
dtypes: float64(2), int64(23), object(12)
memory usage: 438.8+ KB

In [22]:
df.describe()

,Age,DailyRate,DistanceFromHome(KM),Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience(Years),TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
count,1478.000000,1478.000000,1478.000000,1478.000000,1478.0,1478.000000,1478.000000,1478.000000,1478.000000,1478.000000,...,1478.000000,1478.0,1478.000000,1478.000000,1478.000000,1478.000000,1478.000000,1478.000000,1478.000000,1478.000000
mean,36.950609,801.081191,9.221922,2.910014,1.0,1034.174560,2.725981,2.731394,2.066306,2.720568,...,2.707713,80.0,0.790257,11.290934,2.797700,2.759134,7.014208,4.225304,2.182679,4.073072
std,9.090510,403.205202,8.121755,1.024094,0.0,606.626125,1.092853,0.711813,1.105627,1.103817,...,1.082805,0.0,0.849939,7.771661,1.289642,0.707945,6.118482,3.616330,3.221109,3.488846
min,19.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,494.250000,2.000000,2.000000,1.000000,2.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1029.500000,3.000000,3.000000,2.000000,3.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1572.750000,4.000000,3.000000,3.000000,4.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,4.000000,5.000000,4.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [24]:
df.to_csv('hr_01.csv',index =False)
print("file saved")

file saved

In [25]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome(KM)', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'SalarySlab', 'HourlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'SalaryHike %',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardWorkingHours',
       'StockOptionLevel', 'TotalExperience(Years)', 'TrainingsLastYear',
       'WorkLifeBalance', 'YearsatCompany', 'YearsinCurrentRole',
       'YearsSincePromotion', 'YearsWithCurrManager'],
      dtype='object')

In [26]:
df.rename(columns={'DistanceFromHome(KM)': 'DistanceFromHome_KM',
                    'SalaryHike %':'SalaryHike_Percent',
                   'TotalExperience(Years)':'TotalExperience_Years'
                  }, inplace =True)

In [27]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome_KM', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'SalarySlab', 'HourlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'SalaryHike_Percent',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardWorkingHours',
       'StockOptionLevel', 'TotalExperience_Years', 'TrainingsLastYear',
       'WorkLifeBalance', 'YearsatCompany', 'YearsinCurrentRole',
       'YearsSincePromotion', 'YearsWithCurrManager'],
      dtype='object')

In [28]:
df.to_csv('hr_01.csv',index =False)
print("file saved")

file saved

In [29]:
df['EmpID'].duplicated().sum()

np.int64(14)

In [30]:
df[df['EmpID'].duplicated(keep=False)].sort_values('EmpID')

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome_KM,Education,EducationField,...,RelationshipSatisfaction,StandardWorkingHours,StockOptionLevel,TotalExperience_Years,TrainingsLastYear,WorkLifeBalance,YearsatCompany,YearsinCurrentRole,YearsSincePromotion,YearsWithCurrManager
638,VK11320,34,26-35,No,Travel-Frequently,653,Administration,10,4,Technical Degree,...,2,80,1,8,3,2,8,2,7,2.0
637,VK11320,34,26-35,No,Travel-Frequently,653,Administration,10,4,Technical Degree,...,2,80,1,8,3,2,8,2,7,7.0
520,VK13760,32,26-35,Yes,Travel-Frequently,238,Administration,5,2,Life Sciences,...,1,80,0,8,2,3,4,1,0,0.0
513,VK13760,32,26-35,Yes,Travel-Frequently,238,Administration,5,2,Life Sciences,...,1,80,0,8,2,3,4,1,0,3.0
70,VK14390,23,18-25,Yes,Travel-Frequently,638,Sales,9,3,Marketing,...,1,80,1,1,3,2,1,0,1,0.0
77,VK14390,23,18-25,Yes,Travel-Frequently,638,Sales,9,3,Marketing,...,1,80,1,1,3,2,1,0,1,1.0
327,VK14610,29,26-35,No,Travel_Rarely,468,Administration,28,4,Medical,...,2,80,0,5,3,1,5,4,0,4.0
328,VK14610,29,26-35,No,Travel_Rarely,468,Administration,28,4,Medical,...,2,80,0,5,3,1,5,4,0,4.0
1336,VK14620,50,46-55,Yes,Travel_Rarely,410,IT,28,3,Marketing,...,2,80,1,20,3,3,3,2,2,0.0
1335,VK14620,50,46-55,Yes,Travel_Rarely,410,IT,28,3,Marketing,...,2,80,1,20,3,3,3,2,2,0.0
954,VK14630,39,36-45,No,Travel_Rarely,722,IT,24,1,Marketing,...,1,80,1,21,2,2,20,9,9,6.0
952,VK14630,39,36-45,No,Travel_Rarely,722,IT,24,1,Marketing,...,1,80,1,21,2,2,20,9,9,6.0
457,VK14640,31,26-35,No,Non-Travel,325,Administration,5,3,Medical,...,2,80,0,10,2,3,9,4,1,7.0
458,VK14640,31,26-35,No,Non-Travel,325,Administration,5,3,Medical,...,2,80,0,10,2,3,9,4,1,7.0
162,VK14650,26,26-35,No,Travel_Rarely,1167,Sales,5,3,Other,...,4,80,0,5,2,3,4,2,0,5.0
161,VK14650,26,26-35,No,Travel_Rarely,1167,Sales,5,3,Other,...,4,80,0,5,2,3,4,2,0,0.0
802,VK14660,36,36-45,No,Travel-Frequently,884,Operations,23,2,Medical,...,3,80,1,17,3,3,5,2,0,3.0
803,VK14660,36,36-45,No,Travel-Frequently,884,Operations,23,2,Medical,...,3,80,1,17,3,3,5,2,0,2.0
955,VK14670,39,36-45,No,Travel_Rarely,613,Operations,6,1,Medical,...,1,80,1,9,5,3,7,7,1,1.0
953,VK14670,39,36-45,No,Travel_Rarely,613,Operations,6,1,Medical,...,1,80,1,9,5,3,7,7,1,7.0
211,VK14680,27,26-35,No,Travel_Rarely,155,Administration,4,3,Life Sciences,...,2,80,1,6,0,3,6,2,0,3.0
210,VK14680,27,26-35,No,Travel_Rarely,155,Administration,4,3,Life Sciences,...,2,80,1,6,0,3,6,2,0,3.0
1304,VK14690,49,46-55,No,Travel-Frequently,1023,IT,2,3,Medical,...,4,80,0,17,3,2,9,6,0,8.0
1305,VK14690,49,46-55,No,Travel-Frequently,1023,IT,2,3,Medical,...,4,80,0,17,3,2,9,6,0,8.0
655,VK14700,34,26-35,No,TravelRarely,628,Administration,8,3,Medical,...,1,80,0,6,3,4,4,3,1,2.0
654,VK14700,34,26-35,No,TravelRarely,628,Administration,8,3,Medical,...,1,80,0,6,3,4,4,3,1,2.0
429,VK9530,31,26-35,Yes,Travel-Frequently,1060,Sales,1,3,Life Sciences,...,1,80,0,3,2,4,3,2,2,0.0
428,VK9530,31,26-35,Yes,Travel-Frequently,1060,Sales,1,3,Life Sciences,...,1,80,0,3,2,4,3,2,2,2.0

In [31]:
df[df['EmpID'].duplicated(keep=False)]['EmpID'].unique()

array(['VK14390', 'VK14650', 'VK14680', 'VK14610', 'VK9530', 'VK14640',
       'VK13760', 'VK11320', 'VK14700', 'VK14660', 'VK14630', 'VK14670',
       'VK14690', 'VK14620'], dtype=object)

In [32]:
df =df.drop_duplicates(subset=['EmpID'],keep='first')

In [33]:
df['EmpID'].duplicated().sum()

np.int64(0)

In [34]:
df.shape

(1464, 37)

In [35]:
df.to_csv("hr_01.csv",index=False)
print("file update")

file update